spring:
  datasource:
    username: postgres
    password: post@123
    url: jdbc:postgresql://192.168.1.245:5432/pg_3Dscene
    driver-class-name: org.postgresql.Driver
server:
  port: 80
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.com.kxyt.entity
