# OSS相关配置信息
aliyun:
  oss:
    # oss对外服务的访问域名
    endpoint: oss-cn-beijing.aliyuncs.com
    # 访问身份验证中用到用户标识
    accessKeyId: LTAI4G62eKydaSv41EkqVgDf
    # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    accessKeySecret: kM4IWaltfpPQ2uR3d8OcFqu1bdfaSy
    # oss的存储空间
    bucketName: skyforrun-oss
    policy:
      # 签名有效期(S)
      expire: 300
    # 上传文件大小(M)
    maxSize: 10
    # 文件上传成功后的回调地址
    callback: http://localhost/aliyun/oss/callback
    dir:
      # 上传文件夹路径前缀
      prefix: test/
server:
  ssl:
    # 证书位置
    key-store: classpath:server.psf
    # 证书加密方式
    key-store-type: jks
    # 证书加密面膜
    key-store-password: 123456
#    key-alias: server
  port: 443
spring:
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: HTML5
    cache: false
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.217:3306/zj_test?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  datasource2:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.217:3306/mysql?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
#elasticsearch 和 二维码 专用
  datasource3:
    username: root
    password: 7495
    url: jdbc:mysql://127.0.0.1:3306/world?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  #ES相关配置
  elasticsearch:
    rest:
      uris: localhost:9200
  security:
    user:
      name: root
      password: root
  #邮箱相关配置
  mail:
    host: smtp.qq.com
    port: 465
    username: 1262345715@qq.com
    password: umczfrwliutkjbcb
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.ssl.enable: true
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
#spring session配置，实现session共享，重启程序session不失效
  session:
    store-type: redis
    redis:
      flush-mode: immediate
      namespace: "spring:session"
  #redis相关配置
#  redis:
#    # Redis数据库索引（默认为0）
#    database: 0
#    # Redis服务器地址
#    host: 39.99.140.108
#    # Redis服务器连接端口
#    port: 6379
#    # Redis服务器连接密码（默认为空）
#    password:
#    timeout: 10000
#    lettuce:
#      pool:
#        # 连接池最大连接数（使用负值表示没有限制） 默认 8
#        max-active: 8
#        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
#        max-wait: -1
#        # 连接池中的最大空闲连接 默认 8
#        max-idle: 8
#        # 连接池中的最小空闲连接 默认 0
#        min-idle: 0
  kafka:
    bootstrap-servers: 33.99.140.108:9060,33.99.140.108:9061,33.99.140.108:9062
    consumer:
      group-id: 0
      #key-value序列化与反序列化
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      #每个批次发送消息的数量
      batch-size: 65536
      #缓冲区大小
      buffer-memory: 524288
logging:
  level:
   com.hgnu.study: debug
 #  org.springframework.security: trace
xxl:
  job:
    admin:
      # 调度中心部署跟地址 [选填]：如调度中心集群部署存在多个地址则用逗号分隔。执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"；为空则关闭自动注册；
      addresses: http://localhost:8080/xxl-job-admin
    executor:
      # 执行器IP [选填]：默认为空表示自动获取IP，多网卡时可手动设置指定IP，该IP不会绑定Host仅作为通讯实用；地址信息用于 "执行器注册" 和 "调度中心请求并触发任务"；
      ip:
      # 执行器端口号 [选填]：小于等于0则自动获取；默认端口为9999，单机部署多个执行器时，注意要配置不同执行器端口；
      port: 9999
      # 执行器运行日志文件存储磁盘路径 [选填] ：需要对该路径拥有读写权限；为空则使用默认路径；
      logpath: ./logs/jobhandler
      # 执行器AppName [选填]：执行器心跳注册分组依据；为空则关闭自动注册
      appname: plat-job
      # 执行器日志保存天数 [选填] ：值大于3时生效，启用执行器Log文件定期清理功能，否则不生效；
      log-retention-days: -1
    # 执行器通讯TOKEN [选填]：非空时启用；
    accessToken:

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
