server:
  ssl:
    # 证书位置
    key-store: classpath:server.psf
    # 证书加密方式
    key-store-type: jks
    # 证书加密面膜
    key-store-password: 123456
#    key-alias: server
  port: 443
spring:
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: HTML5
    cache: false
  datasource:
    username: postgres
    password: post@123
    url: jdbc:postgresql://192.168.1.245:5432/pg_byne
    driver-class-name: org.postgresql.Driver
  datasource2:
    username: postgres
    password: post@123
    url: jdbc:postgresql://192.168.1.245:5432/pg_3Dscene
    driver-class-name: org.postgresql.Driver
  datasource3:
    username: root
    password: 7495
    url: jdbc:mysql://127.0.0.1:3306/world?serverTimezone=UTC&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  #ES相关配置
  elasticsearch:
    rest:
      uris: localhost:9200
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 39.99.140.108
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    timeout: 10000
  kafka:
    bootstrap-servers: 33.99.140.108:9060,33.99.140.108:9061,33.99.140.108:9062
    consumer:
      group-id: 0
      #key-value序列化与反序列化
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      #每个批次发送消息的数量
      batch-size: 65536
      #缓冲区大小
      buffer-memory: 524288
logging:
  level:
   cn.com.kxyt: debug
xxl:
  job:
    admin:
      # 调度中心部署跟地址 [选填]：如调度中心集群部署存在多个地址则用逗号分隔。执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"；为空则关闭自动注册；
      addresses: http://192.168.1.12:8080/xxl-job-admin
    executor:
      # 执行器IP [选填]：默认为空表示自动获取IP，多网卡时可手动设置指定IP，该IP不会绑定Host仅作为通讯实用；地址信息用于 "执行器注册" 和 "调度中心请求并触发任务"；
      ip:
      # 执行器端口号 [选填]：小于等于0则自动获取；默认端口为9999，单机部署多个执行器时，注意要配置不同执行器端口；
      port: 9999
      # 执行器运行日志文件存储磁盘路径 [选填] ：需要对该路径拥有读写权限；为空则使用默认路径；
      logpath: ./logs/jobhandler
      # 执行器AppName [选填]：执行器心跳注册分组依据；为空则关闭自动注册
      appname: plat-job
      # 执行器日志保存天数 [选填] ：值大于3时生效，启用执行器Log文件定期清理功能，否则不生效；
      log-retention-days: -1
    # 执行器通讯TOKEN [选填]：非空时启用；
    accessToken:
