server:
  ssl:
    key-store: classpath:server.psf
    key-store-type: jks
    key-store-password: 123456
#    key-alias: server
  port: 8088
spring:
  datasource:
    username: postgres
    password: post@123
    url: jdbc:postgresql://192.168.1.245:5432/pg_byne
    driver-class-name: org.postgresql.Driver
  datasource2:
    username: postgres
    password: post@123
    url: jdbc:postgresql://192.168.1.245:5432/pg_3Dscene
    driver-class-name: org.postgresql.Driver
  datasource3:
    username: root
    password: 7495
    url: jdbc:mysql://127.0.0.1:3306/mybatis?serverTimezone=UTC&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
   cn.com.kxyt: debug